# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ywlke/JHU/1112/S1-AlgorithmsRobotics-Hager/FinalProject/cochleamp/CppManipPFP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ywlke/JHU/1112/S1-AlgorithmsRobotics-Hager/FinalProject/cochleamp/CppManipPFP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ywlke/JHU/1112/S1-AlgorithmsRobotics-Hager/FinalProject/cochleamp/CppManipPFP/CMakeFiles /home/ywlke/JHU/1112/S1-AlgorithmsRobotics-Hager/FinalProject/cochleamp/CppManipPFP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ywlke/JHU/1112/S1-AlgorithmsRobotics-Hager/FinalProject/cochleamp/CppManipPFP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Planner

# Build rule for target.
Planner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Planner
.PHONY : Planner

# fast build rule for target.
Planner/fast:
	$(MAKE) -f CMakeFiles/Planner.dir/build.make CMakeFiles/Planner.dir/build
.PHONY : Planner/fast

# target to build an object file
src/Graphics.o:
	$(MAKE) -f CMakeFiles/Planner.dir/build.make CMakeFiles/Planner.dir/src/Graphics.o
.PHONY : src/Graphics.o

# target to preprocess a source file
src/Graphics.i:
	$(MAKE) -f CMakeFiles/Planner.dir/build.make CMakeFiles/Planner.dir/src/Graphics.i
.PHONY : src/Graphics.i

# target to generate assembly for a file
src/Graphics.s:
	$(MAKE) -f CMakeFiles/Planner.dir/build.make CMakeFiles/Planner.dir/src/Graphics.s
.PHONY : src/Graphics.s

# target to build an object file
src/ManipPlanner.o:
	$(MAKE) -f CMakeFiles/Planner.dir/build.make CMakeFiles/Planner.dir/src/ManipPlanner.o
.PHONY : src/ManipPlanner.o

# target to preprocess a source file
src/ManipPlanner.i:
	$(MAKE) -f CMakeFiles/Planner.dir/build.make CMakeFiles/Planner.dir/src/ManipPlanner.i
.PHONY : src/ManipPlanner.i

# target to generate assembly for a file
src/ManipPlanner.s:
	$(MAKE) -f CMakeFiles/Planner.dir/build.make CMakeFiles/Planner.dir/src/ManipPlanner.s
.PHONY : src/ManipPlanner.s

# target to build an object file
src/ManipSimulator.o:
	$(MAKE) -f CMakeFiles/Planner.dir/build.make CMakeFiles/Planner.dir/src/ManipSimulator.o
.PHONY : src/ManipSimulator.o

# target to preprocess a source file
src/ManipSimulator.i:
	$(MAKE) -f CMakeFiles/Planner.dir/build.make CMakeFiles/Planner.dir/src/ManipSimulator.i
.PHONY : src/ManipSimulator.i

# target to generate assembly for a file
src/ManipSimulator.s:
	$(MAKE) -f CMakeFiles/Planner.dir/build.make CMakeFiles/Planner.dir/src/ManipSimulator.s
.PHONY : src/ManipSimulator.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Planner"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Graphics.o"
	@echo "... src/Graphics.i"
	@echo "... src/Graphics.s"
	@echo "... src/ManipPlanner.o"
	@echo "... src/ManipPlanner.i"
	@echo "... src/ManipPlanner.s"
	@echo "... src/ManipSimulator.o"
	@echo "... src/ManipSimulator.i"
	@echo "... src/ManipSimulator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

